baseURL = "http://abs-models.org/"
languageCode = "en-us"
title = "The ABS Modeling Language"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionnality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "abs"
